# Generated by Django 5.0.1 on 2024-03-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_set', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
