# Generated by Django 5.0.1 on 2024-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='author',
            new_name='user',
        ),
    ]
